### PR TITLE
fix compilation error in Telemetry

### PR DESCRIPTION
**Pull request by patriknw**
* and some more minor cleanup there

### CODE REVIEW

File: akka-projection-core/src/main/scala/akka/projection/internal/Telemetry.scala [hunk 1]
```diff
@@ -102,7 +103,7 @@ trait Telemetry {
 
   override def stopped(): Unit = {}
 
-  override def beforeProcess[Envelope](envelope: Envelope): AnyRef = Unit
+  override def beforeProcess[Envelope](envelope: Envelope): AnyRef = NotUsed
```
Comment (patriknw) [inline akka-projection-core/src/main/scala/akka/projection/internal/Telemetry.scala:106]: that didn't compile with Scala 2.13

**Comment by patriknw** [comment]
I'm not sure how this slipped in. We compile with 2.13 on Travis. Maybe it's something with publishLocal (scaladoc) because that was how I found it.

**Comment by patriknw** [comment]
another of that JdbcProjectionSpec (we'll have to allocate some time next sprint to get the tests in shape)
