### ISSUE TITLE
ProjectionTestKit not working with Akka 2.6.10

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#466]
@johanandren said: Non source compatible change in Java testkit (akka/akka#29677 to allow throwing checked exceptions in awaitAssert). Should usually be use with lambdas but it seems as in the projection testkit we use it.

```
java.lang.NoSuchMethodError: akka.actor.testkit.typed.javadsl.TestProbe.awaitAssert(Ljava/time/Duration;Ljava/time/Duration;Ljava/util/function/Supplier;)Ljava/lang/Object;
820	at akka.projection.testkit.javadsl.ProjectionTestKit.runInternal(ProjectionTestKit.scala:109)
821	at akka.projection.testkit.javadsl.ProjectionTestKit.run(ProjectionTestKit.scala:55)
822	at sample.cqrs.ProjectionTest.projectionShouldPublishEventsToSystemEventStream(ProjectionTest.java:88)
```

Let's release a new Projections with updated Akka dependency.
